data = {'Карта Побыту' : 'Здесь вы можете найти документы https://immcongroup.com/karta-pobytu ',
        'Банк' : 'Пишите этим людям, сейчас таких людей нет, но вы можете им стать пишите сюда @nikshut',
        'Счёт' :'Пишите этим людям, сейчас таких людей нет, но вы можете им стать пишите сюда @nikshut',
        'Страховка' : 'Здесь вы можете получить страховку https://goo.gl/maps/sT2MGxk6hpYN584SA',
        'Где можно сделать страховку?' : 'Здесь вы можете получить страховку https://goo.gl/maps/sT2MGxk6hpYN584SA',
        'Выписка' : 'Пишите этим людям, сейчас таких людей нет, но вы можете им стать пишите сюда @nikshut',
        'Uber' : 'I just invited you to drive with Uber. Sign up and earn up to zł100 extra after completing your first 50 trips. https://www.uber.com/signup/drive/deliver/?invite_code=fcs7vhdxq',
        'Коронавирус' : 'https://www.gov.pl/web/koronawirus/aktualne-zasady-i-ograniczenia',
        'Нужно ли сидеть карантин студентам?' : 'Студентам нет, туристам/работникам - да',
        'Можно заехать по безвизу?' : 'Безвиз с Польшей закрыт, нужно иметь студ.визу или карту побыту и подтверждение что ты студент',
        'Безвиз' : 'Безвиз с Польшей закрыт, нужно иметь студ.визу или карту побыту и подтверждение что ты студент',
        'Нужно ли носить маску?' : 'Так как Краков находится в красной зоне вы должны носить маску на улице и в общественных местах',
        'Карантин' : 'Студентам нет, туристам/работникам - да',
        'Где купить еду в воскресенье?' : 'Carrefour 24/7 Express, Biedronka Dworzec Glowny, Zabka 12:00 - 21:00',
        'Воскресенье' : 'Carrefour 24/7 Express, Biedronka Dworzec Glowny, Zabka 12:00 - 21:00',
        'Продукты воскресенье' : 'Carrefour 24/7 Express, Biedronka Dworzec Glowny, Zabka 12:00 - 21:00',
        'Надо сдавать тест?' : 'Нет, на коронавирус не надо делать',
        'Надо сдавать тест на коронавирус?' : 'Нет, на коронавирус не надо делать',
        'Тест на коронавирус' :'Нет, на коронавирус не надо делать',
        'Тест' : 'Нет, на коронавирус надо нужно делать',
        'Сейчас тем кто въезжает в Украину с Польши тест надо сдавать ?' : 'Нет, на коронавирус не надо делать',
        'В каком банке посоветуете открыть счёт?' : 'Millenium Bank https://www.bankmillennium.pl/lubietopolecam?id=25653720',
        'где можно пожарить шашлыки?' : 'Bagry, Kryspinow',
        'Как начать работу в Uber Eats?' : 'I just invited you to drive with Uber. Sign up and earn up to zł200 extra after completing your first 50 trips. https://www.uber.com/signup/drive/deliver/?invite_code=tg189nv7e',
        'Uber Eats' : 'I just invited you to drive with Uber. Sign up and earn up to zł200 extra after completing your first 50 trips. https://www.uber.com/signup/drive/deliver/?invite_code=tg189nv7e',
        'Убер' : 'I just invited you to drive with Uber. Sign up and earn up to zł200 extra after completing your first 50 trips. https://www.uber.com/signup/drive/deliver/?invite_code=tg189nv7e',
        'Какие есть купоны?' : 'Bolt, FreeNow, GoodLood, Uber, UberEats',
        'Убер итс' : 'I just invited you to drive with Uber. Sign up and earn up to zł200 extra after completing your first 50 trips. https://www.uber.com/signup/drive/deliver/?invite_code=tg189nv7e'
        }
